### ISSUE TITLE
Check functions in all OpenFaaS namespaces

### ISSUE THREAD

**Issue by welteki** [openfaas/config-checker#8]
Run the function check for functions in all OpenFaaS namespaces, not only the hard coded namespaces.

## Expected Behaviour

Check functions in all OpenFaaS namespaces.

## Current Behaviour

Only checks function in hard coded namespaces.

## Possible Solution

Look for namespaces that have an annotation `openfaas="1"` and check these namespaces.

**Comment by alexellis** [comment]
> Look for namespaces that have an annotation openfaas="1" and check these namespaces.

I think we already do this, so it's just a case of iterating around them now and doing similar logic/checks to the ones we do for the openfaas-fn namespace.
